version: '3.7'

networks:
  my_network:
    name: 'my_network'

services:
  angular:
    image: my-app
    ports:
      - 80:80
    
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:14
    networks:
      - my_network
    volumes:
      - ./Database/database.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - .env
    ports:
      - 5432:5432

  login:
    build:
      context: ./Backend
      dockerfile: dockerfile
    container_name: login_service
    networks:
    - my_network
    depends_on:
    - postgresql
    ports:
    - 3000:3000
  